### ISSUE TITLE
Security questions

### ISSUE THREAD

**Issue by elisseck** [bmoreinis/fakenews#20]
Hello!

I just want to take care to think about security risks here because I don't believe you're running this on it's own server, currently (correct?).

1) Authentication in server.js... I see you've left the db credentials out of the git file (yay) - but would this just be sitting in plain text in the server.js file? Does the node server app have it's own user with restricted permissions? Might be (even just a tiny bit) better to store the creds in another file/directory that has the file permissions locked down to only the node server user. Nothing will be perfect because the server needs automated access but it's better than sitting right in the server.js file, right?

2) Sanitizing user input - I _think_ sequelize does this for us... but we should do a bit of research just to be sure. We could do our own sanitize as well on submit if we decide it's important.

**Comment by bmoreinis** [comment]
Hi, Eli.

cc'ing Stan in case I'm wrong ...

> I just want to take care to think about security risks here because I 
> don't believe you're running this on it's own server, currently 
> (correct?).
>
Nope. On my web server, via proxy, at 
http://app.fakenewsfitness.org:8080. ALTHOUGH that doesn't seem to be 
working right now. I need to talk to Stan.
>
> 1.
>
>     Authentication in server.js... I see you've left the db
>     credentials out of the git file (yay) - but would this just be
>     sitting in plain text in the server.js file?
>
You can't view that file over the web.  You can post to it using port 
8080 ... but not view it.
>
> 1.
>
>     Does the node server app have it's own user with restricted
>     permissions?
>
It can be run by anyone and it stays running now - I installed PM which 
keeps it going.
>
> 1.
>
>     Sanitizing user input - I /think/ sequelize does this for us...
>     but we should do a bit of research just to be sure. We could do
>     our own sanitize as well on submit if we decide it's important.
>
Yes, Sequelize does: https://github.com/sequelize/sequelize/issues/351

Either data comes in the form we are looking for, in which case it is 
put into fields as the appropriate type (and none of our fields are 
executed), or it's ignored: see #77 
http://stackoverflow.com/questions/139199/can-i-protect-against-sql-injection-by-escaping-single-quote-and-surrounding-use. 


Otherwise, REST doesn't include MySQL queries and doesn't need to be 
sanitized.

-Bram

-- 

Martin Bram Moreinis, Designer/Developer
http://myinstructionaldesigns.com
(413) 829-0355

**Comment by elisseck** [comment]
Okay great! Sounds like you've already taken care of this.

Just thought of these things this morning and wanted to check in on it.
