### ISSUE TITLE
Force time delay on submit until WHOIS returns data or timeout

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#29]
When people move the slider to "filled form" this should trigger a replacement of the "Submit" button with an animated Timer gif.  

The submit button gets returned once we have data from BulkWHOIS, or after a set period of time.  

(You can click on the animated GIF and submit anyway - secret feature).

**Comment by elisseck** [comment]
I'm actually not 100% sure there was a timing issue in the end... I think we were running into a new case I just discovered where bulkapi had too many requests at once... and then if you click again it works because they stop.

Will need to look into this further before fixing... but I think it's something that will go away when we move towards production with a live lookup service.
