### ISSUE TITLE
Show via Favicon of Edited Extension

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#52]
I think we want to make it clear whether we are using the FULL FORM or a MODIFIED FORM. I want to use the RED favicon for the modified form, and the green one for the full form.   I would have two icons added, as iconr (red) and icong (green - the default).  Both are attached below. Can you programmatically substitute the red for the green based on whether the JSON file has been edited? 

-     AUTOMATIC WAY: Check if date modified of the config.json file is later than the date modified of the content.js file...
-     MANUAL WAY: if someone manually changes a value or code at the top of the config.json file? 

-Bram

![iconr](https://cloud.githubusercontent.com/assets/4763057/25019553/f440663a-2058-11e7-8724-fee2dfbf2592.png)
![icong](https://cloud.githubusercontent.com/assets/4763057/25019555/f6335c72-2058-11e7-92ea-96a67df91216.png)

**Comment by elisseck** [comment]
I don't think there is a way to programmatically change the icon, since the image is just a path configured in the manifest which is just JSON... so there isn't any logic available there.

**Simple route:** If we aren't going to update code for extensions out in the world, we could just substitute the file when we pull from master for a new version of the extension.

**Slightly more complex:** I think probably what we want to do is fork the repo when we are creating a new version, and add icon.png (and probably config.json) to the .gitignore file in the forked version. That way we can still keep the codebase updated in all but extreme cases with git pull upstream, but retain our configuration and our red icon.

**Comment by bmoreinis** [comment]
You can't ask "is the JSON file updated more recently than the config.js file? ". Ok. Not a big deal now.

Sent from mobile.

--
Bram Moreinis
413-829-0355

**Comment by elisseck** [comment]
Well... we can check the modified date of the file but it's going to be different on each machine when the extension is downloaded.

We could also specify this in config.json, but we would need to change the config, and parse it again in background.js to apply the logic.

Either way we need to specify a 'default' icon that will show up when the extension first loads up, before any logic has a chance to fire, because an extension cannot modify it's own manifest.json, because that would allow it to sneakily give itself more permissions than it tells the user it is getting so it's a huge security problem.

**Comment by bmoreinis** [comment]
Using red icon for GitHub - substitute green when pushing to Chrome Web Store.
