### ISSUE TITLE
Make Download File Format Importable

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#53]
I see two options.  Both do CSV, but one does JSON - yet has fewer users and is older.  The granular mapping of elements in two probably is what sells it ... pick whichever makes sense to you.  

I think use Feed Import if the JSON file can be downloadable and importable, if that's easiest for you; if not, if using CSV, I would use Feeds given user base and update currency. 

Feed Import - https://www.drupal.org/project/feed_import - Stable, 1/7/2015, 6017 users. Formats:

    CSV file
    JSON file - import content from JSON files using path to value
    provide an action if no content was fetched, like providing a default value, skipping item, ...
    detailed reports (if enabled)

Feeds - https://www.drupal.org/project/feeds - Beta 3, 4/9/2017, 117,788 users. Formats and benefits:    

    CSV files
    OPML files
    Granular mapping of input elements to Drupal content elements
    Exportable configurations

**Comment by elisseck** [comment]
Sorry in advance if you get emails while I try to build this parser to work. I just created 36 nodes by accident... meaning to create 1... this is tricky to configure correctly!

**Comment by elisseck** [comment]
Okay so here's where I am at right now ... there are a couple of hard problems left with this. Where is the "import" on your priorities list?

Hard problem #1) The output file needs to be in a different format and it's going to take a couple of hours to get it exporting just right out of the extension. Otherwise feeds attempts to create 36 nodes (the number of fields that are in the export)

Hard problem #2) I got the parsing set up, but feeds is mysteriously creating a second, completely empty node with every import... and there are no error/notice logs and I have no idea why yet... so that is a mystery that may take a long time to unravel.

Out of time for today but there's the update.

**Comment by bmoreinis** [comment]
Take a break and do the groups field (default to development group).  That should be fast.

I will do the display bit. 

Sent from mobile.

--
Bram Moreinis
413-829-0355

**Comment by bmoreinis** [comment]
Output before import of course and take until Thursday.

Sent from mobile.

--
Bram Moreinis
413-829-0355

**Comment by elisseck** [comment]
Since this is technically working... there is just a Drupal configuration problem leading to the small "one additional empty node" bug... I will close this larger issue and we can open a new, low priority one.
