### ISSUE TITLE
Was Ad Ratio Branch:  Now  Two-Pages-New-Fields.

### ISSUE THREAD

**Issue by bmoreinis** [bmoreinis/fakenews#68]
So - there's a new branch, Two-Pages-New-Fields.
https://docs.google.com/document/d/1BJAsFLEN992fL-qreltxvIj1MMrpc4VdAap8yB35tD8/edit#heading=h.lup33t8dmiuh
I tried to break it into two pages of mixed field types.  The form code is HORRENDOUS - would love your help fixing that.  Most likely the one error I see now would be resolved too.  Please help, Eli.

**Comment by bmoreinis** [comment]
So - there's a new branch, Two-Pages-New-Fields.
https://docs.google.com/document/d/1BJAsFLEN992fL-qreltxvIj1MMrpc4VdAap8yB35tD8/edit#heading=h.lup33t8dmiuh
I tried to break it into two pages of mixed field types.  The form code is HORRENDOUS - would love your help fixing that.  Most likely the one error I see now would be resolved too.  Please help, Eli.

**Comment by elisseck** [comment]
What's the timeline on this? There is a lot of work here and I have really limited time this weekend (mothers day stuff and garden plot calls on top of my normal stuff).

If we're doing all of these complex fields on both pages, it makes sense to refactor it to be more general, and we should.

If we're talking about just quick fixes and not making it "good" per-say ... it looks like what you're running into is just mismatching bits of form that have been swapped back and forth between page 1 and page 2 in config.json.

Since page 1 only switches on 'fields[i][3]' and page 2 only switches on 'fieldsP2[i][3]'.... they've got to be in the right switch as it's currently written e.g. not very general.

It looks like "s3" and "s5" at least are in the wrong switch.

It also looks like some of the fieldsP2 elements are still appending themselves to "formName" e.g. page 1 instead of p2form e.g. page 2, so you're getting all of those boxes on page 1.

These are leading to your "cannot set property field of null" error because it can't find the html element to build the object to set the .field property for if it's not generated where expected.

I can try to make some time this weekend to help out here but i'm not sure it will happen - or I can do it next week for sure - or you can give a go at what I just typed out this weekend.

Thoughts?

**Comment by elisseck** [comment]
Oh looks like one more piece of weirdness having to do with the radio buttons...

We can't set the same "likert" value for the name of all of the radio buttons ... if they're within the same form with the same name, they'll act as a radio group and you can only select 1 even if there are two different questions with different sets of options.

We'll need to rename them so each set has a unique name.

**Comment by bmoreinis** [comment]
Hi, Eli. 

I didn't get email notifications for your reply.  Weird! It shows me subscribed. 

> What's the timeline on this? 

Next week the pilot starts, so ... can you di it by Friday? 

> If we're doing all of these complex fields on both pages, it makes sense to refactor it to be more > general

ABSOLUTELY.   I have a few ideas for that - wanted to talk to you tonight about them.  Anyhow - please just reach out when you can. 

> If we're talking about just quick fixes and not making it "good" per-say ... it looks like what 
> you're running into is just mismatching bits of form that have been swapped back and forth 
> between page 1 and page 2 in config.json.

Oh, great.  Yes, that was my suspicion - I wasn't doing anything fancy, so it couldn't be that broken. 

> Since page 1 only switches on 'fields[i][3]' and page 2 only switches on 'fieldsP2[i][3]'.... they've 
> got to be in the right switch as it's currently written e.g. not very general.

OK. Will Fix. 

> It looks like "s3" and "s5" at least are in the wrong switch.

Will Check. 

> It also looks like some of the fieldsP2 elements are still appending themselves to "formName" 
> e.g. page 1 instead of p2form e.g. page 2, so you're getting all of those boxes on page 1.

Thanks!  It's so confusing now with all the replicated code.  I'm learning how to do code folding with SublimeText and that helps. 

> These are leading to your "cannot set property field of null" error because it can't find the html 
> element to build the object to set the .field property for if it's not generated where expected.

Ah!



> We can't set the same "likert" value for the name of all of the radio buttons ... if they're within 
> the same form with the same name, they'll act as a radio group and you can only select 1 even if > there are two different questions with different sets of options.

Ah.  Okay!  I'm on it. 

But this code really needs refactoring ... I think it will be fun to swap ideas with you.  Maybe a lunch?  And -- did you want to learn about Bryan Ollendyke's ELMS project on Wednesday? 

-Bram

**Comment by bmoreinis** [comment]
Dealt with via meeting and planning
